config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :jobs
 root 'jobs#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :category
	belongs_to :user

	has_attached_file :image, styles: { medium: "554x400#" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :find_job, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		if params[:category].blank?
			@jobs = Job.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@jobs = Job.where(category_id: @category_id).order("created_at DESC")	
		end	
	end
	def show
		
	end
	def new
		@job = current_user.jobs.build
	end
	def create
		@job = current_user.jobs.build(jobs_params)

		if @job.save
			redirect_to @job
		else
			render "New"
		end		
	end
	def edit
			
	end
	def update
		if @job.update(jobs_params)
			redirect_to @job
		else
			render "Edit"
		end			
	end
	def destroy
		@job.destroy
		redirect_to root_path	
	end

	private

	def jobs_params
		params.require(:job).permit(:title, :description, :company, :url, :category_id, :image)	
	end	
	def find_job
		@job = Job.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for @job, html: { multipart: true, class: 'form-vertical' } do |f|
	.form-inputs
		= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category" }, input_html: { class: "btn btn-default dropdown-toggle" }
		%br
		%br
		= f.input :title, label: "Job Title", input_html: { class: "form-inputs" }
		.form-group
			= f.label :image
			%br
			= f.file_field :image
		= f.input :description, label: "Job Description", input_html: { class: "form-inputs" }
		= f.input :company, label: "Your Company", input_html: { class: "form-inputs" }
		= f.input :url, label: "Link to Job", input_html: { class: "form-inputs" }
	%br/
	= f.button :submit, class: "btn btn-primary"

app/views/jobs/edit.html.haml
%h1 Edit Job

= render 'form'

= link_to "Back", root_path

app/views/jobs/index.html.haml
#jobs
	- @jobs.each do |job|
		.job
			%h2= link_to job.title, job
			%p= job.company
	

app/views/jobs/new.html.haml
%h1 New Job
%br
= render 'form'

= link_to "Back", root_path

app/views/jobs/show.html.haml
#jobs
	.job
		.panel-heading.jobtitle
			%h2= @job.title
		.panel-body
			= image_tag @job.image.url(:medium)		
			%p= @job.description
			%p= @job.company
		%button.btn.btn-default= link_to "Apply for Job", @job						
	#links
		= link_to "Back", root_path, class: "btn btn-sm btn-default"
		- if user_signed_in?
			= link_to "Edit", edit_job_path(@job), class: "btn btn-sm btn-default"
			= link_to "Delete", job_path(@job), method: :delete, data: { confirm: "Are You Sure?" }, class: "btn btn-sm btn-default"

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Job Board
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	%script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"}
	= csrf_meta_tags

%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand Job Board
			%ul.nav.navbar-nav
				%li= link_to "All Jobs", root_path
				- Category.all.each do |category|
					%li= link_to category.name, jobs_path(category: category.name)
			- if user_signed_in?	
				= link_to "New Job", new_job_path, class: "navbar-text navbar-right navbar-link"
				= link_to "Account", edit_user_registration_path, class: "navbar-text navbar-right navbar-link"
				= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-text navbar-right navbar-link"
			- else
				= link_to "Sign Up", new_user_registration_path, class: "navbar-text navbar-right navbar-link" 
				= link_to "Sign In", new_user_session_path, class: "navbar-text navbar-right navbar-link"
	.container
		.panel.panel-default
			.panel-body
				.row
					.col-md-6.col-sm-6	
						= yield	